services:
  discord-mc-bot:
    build: .
    container_name: discord-mc-bot
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Dock/docker/discord:/app/host_config:ro
    pull_policy: if_not_present